### ISSUE TITLE
Make the weapons that can kill vampires configurable

### ISSUE THREAD

**Issue by Tankuu** [williambl/haema#26]
Some mods add weapons such as wooden daggers or wooden spears and such, which I feel like would fit as a killing tool in my modpack :)

**Comment by williambl** [comment]
It is configurable via datapack - the item tag "haema:vampire_weapons" :)

**Comment by Tankuu** [comment]
Ah, sweet! Thanks for letting me know. If you haven't already it may be important to put that on your mod page. If you have, then... again, I'm sorry haha

If you have any easy tutorials that let me know how to make a data pack such as this one let me know, as I'm entirely new to data packs :) However I'll do some research myself as well!

It may a good idea to implement this into the mod itself as well as some people may want it to be mod-specific rather than world-specific (as I believe that's how data packs work?). I may be wrong in that assumption of how data packs work, and if I am let me know :)

**Comment by williambl** [comment]
I do have quite a big issue with features in the mod not being very discoverable. I might make a wiki or something when I have time.

The main reason I went with datapacks and game rules for configuration rather than traditional config files is that datapacks and game rules make it much easier for server managers and modpack makers to create configurations that can be shared and combined.

**Comment by Tankuu** [comment]
I may be willing to help with setting up a wiki, mostly just because that's something I find fun lol.

Upon learning how to create data packs I actually agree, it is quite easy. I believe there is also a Fabric mod out there that adds data packs to every world created (not 100% sure).
