### ISSUE TITLE
Haema causes crash upon load after first load with vampire origin

### ISSUE THREAD

**Issue by MitztheKat** [williambl/haema#60]
[latest.log](https://github.com/williambl/haema/files/6414927/latest.log)

Attempting to load a save with haema seems to crash the game, which means any game previously loaded with haema is now void.
This has been going on for several versions now; can you look into my modlist to see what mod causes it, and see if you can make a patch on your end?
I love the haema mod, but it locking games after first use is very... depressing.
Thanks.
https://drive.google.com/file/d/1TAXbnPgYssJbLuZDpZacP70NgwEtzzuV/view?usp=sharing

**Comment by masonbooh** [comment]
im having a similar problem but whenever i load up minecraft with haema it just crashes

i realy hope someone comes to fix this

**Comment by nxghtmvrx** [comment]
I've been trying to track this for quite some time. It seems as it can start as #37 and after several(was 4 for me) ruined worlds starts to crash server/integrated server on world join making it impossible to join any world. Main issue always remain the same as in MitztheKat log: ticking player. [Here's my very similar output from integrated server.](https://gist.githubusercontent.com/natanfudge/7dfd539023cb660e95bb4c6a2b97bba7/raw/4169b9eae48b86b6df34c649fad7204e3e2e6e42/crash.txt) I can provide full client log if needed, but since it happens exclusively on integrated server side, there won't be much more info.

**Comment by williambl** [comment]
Looks like another mod is doing something that assumes nobody messes with the hungermanager - but haema does. Could I have your modlist @nxghtmvrx ?

**Comment by williambl** [comment]
Actually never mind, try without Spice Of Fabric.

**Comment by nxghtmvrx** [comment]
Thanks! Reported on SoF side. Should solve crash for @MitztheKat too.
